import os
import json
from typing import AsyncGenerator, Optional
from pydantic import BaseModel, Field
from google.adk.agents import Agent, LlmAgent, BaseAgent, SequentialAgent, InvocationContext
from google.adk.events import Event
from .products import products, product_counts, reorder_status

model = "gemini-2.5-flash"

def read_prompt(filename):
    script_dir = os.path.dirname(os.path.abspath(__file__))
    file_path = os.path.join(script_dir, "../prompts", filename)
    with open(file_path, "r") as f:
        return f.read()

# Shared dictionary for reorder status (if not imported from products, define here, but it seems it was added to imports)
# reorder_status was added to imports in previous steps.

def check_inventory(product_id: str):
    """Checks if a product is in stock.

    Args:
        product_id: The ID of the product to check.
    """
    if product_id in products:
        count = product_counts.get(product_id, 0)
        return {"product_id": product_id, "in_stock": count > 0, "count": count}
    else:
        return {"error": "Product ID not found"}

def check_reorder_status(product_id: str):
    """Checks and sets the reorder status for a product.

    Args:
        product_id: The ID of the product to check.
    """
    base_data = check_inventory(product_id)
    if "error" in base_data:
        return base_data
    
    if product_id not in reorder_status:
        reorder_status[product_id] = "ORDERING"
    
    base_data["reorder_status"] = reorder_status[product_id]
    return base_data

class InventoryData(BaseModel):
    product_id: str = Field(description="The product ID checked.")
    in_stock: bool = Field(description="Whether the product is in stock.")
    count: int = Field(description="The quantity available.")
    reorder_status: Optional[str] = Field(description="The reorder status of the product.", default=None)

inventory_instruction = read_prompt("inventory-prompt.txt")
reorder_instruction = read_prompt("reorder-prompt.txt")

inventory_agent = Agent(
    name="inventory_agent",
    description="Checks product inventory availability.",
    model=model,
    instruction=inventory_instruction,
    tools=[check_inventory],
)

# Renamed from inventory_data_agent
check_inventory_agent = LlmAgent(
    name="check_inventory_agent",
    description="Checks product inventory and returns structured data.",
    model=model,
    instruction="Check the inventory for the given product ID and return the details.",
    tools=[check_inventory],
    output_schema=InventoryData
)

check_reorder_agent = LlmAgent(
    name="check_reorder_agent",
    description="Checks and updates reorder status.",
    model=model,
    instruction=reorder_instruction,
    tools=[check_reorder_status],
    output_schema=InventoryData
)

class PossiblyReorderAgent(BaseAgent):

    reorder_agent: Agent

    def __init__(self, name: str, reorder_agent: Agent):
        super().__init__(
            name=name,
            reorder_agent=reorder_agent
        )

    async def _run_async_impl(self, context: InvocationContext) -> AsyncGenerator[Event, None]:
        # We need the event generated by the "check_inventory_agent" since it
        # included the count as part of its output
        inventory_data = None
        events = context.session.events
        for event in reversed(events):
            if event.author == "check_inventory_agent":
                try:
                    # The content is expected to be a JSON string representing InventoryData
                    if hasattr(event.content, 'parts') and len(event.content.parts) > 0:
                        text = event.content.parts[0].text
                        # It might be wrapped in markdown code block, clean it if necessary
                        if text.startswith("```json"):
                            text = text[7:-3]
                        elif text.startswith("```"):
                            text = text[3:-3]
                        
                        data = json.loads(text)
                        # Validate and create object to ensure type safety
                        inventory_data = InventoryData(**data)
                        break
                except (json.JSONDecodeError, AttributeError, IndexError, ValueError):
                    pass

        if inventory_data and inventory_data.count < 5:
            async for event in self.reorder_agent.run_async(context):
                yield event
        else:
            pass

possibly_reorder_agent = PossiblyReorderAgent(
    name="possibly_reorder_agent",
    reorder_agent=check_reorder_agent
)

inventory_data_agent = SequentialAgent(
    name="inventory_data_agent",
    description="Checks inventory and optionally checks reorder status if stock is low.",
    sub_agents=[check_inventory_agent, possibly_reorder_agent]
)